spring:
  data:
    mongodb:
      uri: mongodb+srv://cerberus6575:B2oba92i@shopcluster-basdw.mongodb.net/shop?retryWrites=true&w=majority
      auto-index-creation: true
    rest:
      default-page-size: 24
  profiles:
    active: dev
  jpa:
    show-sql: true
    generate-ddl: true
  jackson:
    time-zone: Africa/Dakar
  servlet:
    multipart:
      max-request-size: 60MB
      max-file-size: 15MB
  main:
    allow-bean-definition-overriding: true

server:
  port: 8081
  servlet:
    context-path: /api
    encoding:
      enabled: true
      force: true
      charset: UTF-8

logging:
  level:
    root: INFO
#    org.springframework: TRACE
